### PR TITLE
Allow Composite/Multiple Keys

### PR DESCRIPTION
**Pull request by noahcolvin**
Allow classes with more than one `KeyAttribute` defined.

### CODE REVIEW

**Comment by noahcolvin** [comment]
Hey, I just wanted to check back on this. Has anyone had a chance to look at this? Any questions? Thanks!

**Comment by mgasparel** [comment]
Came here to suggest this feature and offer to implement it. I'll try and take a look this week and leave my comments. Hopefully we can get this merged, this is one of the last really big pain points right now.

**Comment by noahcolvin** [comment]
@mgasparel Thanks, I noticed a few issues posted here that this should fix. I've been running off my own fork for a while and it'd be nice to get back on the main package/project with this supported; either with this PR or another if this isn't the direction you want to go.

**Comment by mgasparel** [comment]
I'm actually not a maintainer, just throwing some support behind this because I also need this feature.
There were 2 things I noticed that could use some work.

First, your use of RemoveBrackets() is not dialect-aware (only SQL Server uses square brackets). I solved this by simply using the (unresolved) property name as the parameter name:

`sb.AppendFormat("{0} = @{1}", GetColumnName(idProps[i]), idProps[i].Name);`

Next, I noticed a bit of code duplication, so I opted to wrap up the functionality into a couple functions in SimpleCRUD.cs

`private static void BuildWhereForIdProps(StringBuilder sb, List<PropertyInfo> idProps, object key)`

`private static DynamicParameters GetDynamicParamsForKey(List<PropertyInfo> idProps, object key)`

As this doesn't really affect existing users, and doesn't add undue complexity, I don't personally see any reason for this PR to be rejected. 

Let me know what you think about the feedback

**Comment by ericdc1** [comment]
Thanks for this. I will try to get this reviewed and merged soon.

**Comment by noahcolvin** [comment]
@mgasparel  After ten weeks, I don't remember much of the reasoning behind some of these changes like the `RemoveBrackets()` method :smile:. It does look like your change would work with removing the `RemoveBrackets()` method and would probably be better as it keeps the brackets in the first part for SQL Server. I can make this change.

I can't comment on the rest as I don't know what changes you have/would have made to those methods.

Thanks for taking a look!

**Comment by mgasparel** [comment]
I'm kinda new to OSS, not sure how to approach this.

@ericdc1 Do you want to review and make your own modifications to clean up the duplication? Should I submit my own PR based on the work by @noahcolvin ? Do I have other options I don't even know about?

**Comment by ericdc1** [comment]
thanks

**Pull request merged**
