### PR TITLE
Metadata type attribute support

### PR DESCRIPTION
**Pull request by noahcolvin**
Added support for [MetadataTypeAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.metadatatypeattribute(v=vs.110).aspx).

This is especially useful when using the auto generated class template but you want to add additional attributes to those properties without them being blown away on the next generation.

### CODE REVIEW

**Comment by ericdc1** [comment]
Thanks for working on this. Can you give me an explanation of what this would be used for? I don't think I understand its purpose.

**Comment by noahcolvin** [comment]
I am using your T4 template to generate classes from the database. I have the need to add attributes to these classes such as `[Required]` or `[IgnoreSelect]` but I can't add them to the generated classes directly as they would disappear next time they are regenerated. I also want to avoid changing the template too much.

For example say I have the following class generated from the template:
```csharp
[Table("Dog")]
public partial class Dog
{
  [Key]
  public int ID { get; set; }
  public DateTime Birthdate { get; set; }  
  public int Age { get; set; }
}
```

`Age` is actually a calculated field in SQL, we get that from the current date and the birthdate. `Dapper.SimpleCRUD` can select this fine, but will throw an error when trying to update.

With that generated class in place I can create another partial class and add the attributes there:
```csharp
[MetadataType(typeof(DogMetadata))]
public partial class Dog
{
  internal sealed class DogMetadata
  {
    [ReadOnly(true)]
    public int Age { get; set; }
  }
}
```

Now I can leave the generated class to be changed as needed by the template while still decorating the properties I need for my particular model.

This is also useful for inserting an ID or key field that seems to need a `[Required]` attribute to work.

From what I understand, there are other ORMs and frameworks which also use MetadataTypeAttribute for this exact purpose.

**Comment by noahcolvin** [comment]
Note that I have found a few issues in using it since creating the pull request but I have pushed fixes. I will be unavailable for about a week after this coming Tuesday in the event you have more questions or would like changes. If you wanted to wait for this one and my other PR until I've had much more time to test things I certainly don't mind.

**Comment by ericdc1** [comment]
You can make another partial class and create your additional properties there. Changing the T4 models does not in any way impact those. 

You also can modify the TT file to where template properties generate as virtual properties which can then be overridden in inheriting class if you needs to add Required attribute on them.

Trying to stuff all this in one class you use in your controller is is dangerous / bad practice because of underposting/overposting attacks. See http://www.abhijainsblog.com/2015/04/over-posting-attack-in-mvc.html and http://odetocode.com/blogs/scott/archive/2012/03/11/complete-guide-to-mass-assignment-in-asp-net-mvc.aspx

If you still want to do this, just override the existing properties in the inherited class like this:
    public partial class MyPartial
    {
        public virtual int? Id { get; set; }
    }

    public class MyPartialViewModel : MyPartial
    {
        [Required]
        public override int? Id { get; set; }
    }

Thanks,
Eric

**Comment by noahcolvin** [comment]
The links you posted are related to sending data in the request which is not expected by the controller due to some sort of access restriction in the view. How does that relate to additional attributes being added to properties? Moreover, why is it assumed this will be used with MVC? It's up to the developer to mitigate these attacks which are not relevant to the data access layer.

In this case properties exist because they are a part of a given table and the metadata attributes tell the ORM (or whatever is consuming it) how to handle that data. `System.ComponentModel.DataAnnotations.MetadataTypeAttribute` is the standard way to do this in [Entity Framework](https://www.asp.net/mvc/overview/getting-started/database-first-development/enhancing-data-validation) and [MVC](https://www.asp.net/mvc/overview/older-versions-1/getting-started-with-mvc/getting-started-with-mvc-part7).

Overriding the properties in a subclass to add attributes seems overly complicated for this purpose. To avoid confusion with the rest of the team, I'd probably have to create a subclass for all of the generated classes even if I don't have to add any additional properties or attributes and make sure everyone uses the 'correct' ones. It's also easy to forget to do this when the database changes; there have been a few times already when running the T4 template has been forgotten.

I guess then the only solution is to heavily modify the template to take into account all the possible supported attributes and then add everything that's needed to the `tables` section at the top. I wanted to avoid that because it not the easiest to debug and the more changes we make the more difficult it is to merge any upstream changes you make.

**Comment by Prnda1976** [comment]
@noahcolvin Can you give me a scenario when you would use attributes on your domain models that are not validation attributes such as Required or Range? I agree with Eric that you should exclusively use view models for those and not the models generated by T4 templates because of issues such as underposting or overposting. But even so, if you modify your T4 template to generate partial classes with virtual properties then you can easily extend any of those classes with attributes or overrides. I don't see how is this any more difficult then having to to create meta data classes for your models. Of course this might be a matter of opinion, you are used to do it in one way, I'm used to do it in another, but I would like you to explain why do you feel so strongly about this?

**Comment by noahcolvin** [comment]
@ericdc1 My original example did not use the attributes for validation; I don't intend to use any of the `Dapper.SimpleCRUD` supported attributes for validation. I'm also not using MVC. The links I gave are just examples of other people who had the same issue as myself and solved it in this manner.

The `[Required]` attribute is the only way it seems that `Dapper.SimpleCRUD` will allow me to insert a non-SQL autogenerated key (marked with `[Key]` from the T4 generated code). The `[ReadOnly(true)]` attribute is needed for computed columns where I want the property to be read but SQL will not let you update the field. Basically the same reasons to use any of the attributes `Dapper.SimpleCRUD` currently supports.

I feel strongly about it as I feel like it is the best way to solve the problem out of the solutions given. The `ModelGenerator` T4 template is nice but we've already had to make several changes to it that are unique to our data structure (but don't seem all that uncommon). When it came to this issue, I wanted to see if there was a common way to add attributes to an existing class and I came across `MetadataTypeAttribute` which seemed ideal and it is supported by other frameworks. I figured I could implement it here and people could make use of it if they wish. I would also not have to make use of my fork and be out of sync with other features added in the future.

I don't understand how underposting/overposting applies to using a different class to decorate the properties with attributes, can you please explain?

The property attributes are already supported by `Dapper.SimpleCRUD` so nothing is new there, you can now just tell it to use a different class for the attributes. If I made my own model classes and added all these attributes it would be no different. If I then used these classes as the viewmodel in something like MVC I may have the underposting/overposting issue, but that exists outside `Dapper.SimpleCRUD` and it is not further enabled by `MetadataTypeAttribute`; they are mutually exclusive.

**Pull request closed without merging**
