### PR TITLE
Add DB2 Dialect

### PR DESCRIPTION
**Pull request by dennisbarg**
Added DB2 Dialect in SimpleCRUD.SetDialect()
Added successfully running tests.
Adapted function ResolveTableName and ResolveColumnName in SimpleCRUD for DB2.

This last step was necessary because the default DB2 object names is uppercase. Existing tests did not work with DB2 because the object names (table or column) were not used uniformly in queries. The encapsulation of the object names are only necessary in DB2 if you define the class or the field with an attribute. If this is not done, there is an error message that the object was not found.

### CODE REVIEW

**Comment by ericdc1** [comment]
I appreciate the work on this. Is there a way for me to install db2 to try it out?

**Comment by dennisbarg** [comment]
Try this link. You need an account with IBM. The registration was always free. Use version 11.1. It's the only one available for free.
https://developer.ibm.com/answers/questions/280797/download-db2-express-c-105-1.html

**Comment by ericdc1** [comment]
This is really nice work but I don't have the bandwidth to properly test it. If anyone else is into DB2 and wants this let me know and I can revisit.

**Comment by mvaz77** [comment]
@ericdc1  I am interested too to see DB2.

**Comment by stijwilliams** [comment]
I second this.  We would be willing to run the test and report the results.

**Comment by stijwilliams** [comment]
@ericdc1 - Can we re-open this?  If we can provide some feedback on the unit tests?

**Comment by ericdc1** [comment]
Yes - If you can verify it works, and deal with the merge conflicts so I can accept the PR I will gladly do so.

**Comment by ericdc1** [comment]
added db2 support in another MR.

**Pull request closed without merging**
