### PR TITLE
Creation of the feature CompositePK 

### PR DESCRIPTION
**Pull request by marcusvnac**
I changed the SimpleCRUD to support using tables with composite Primary Keys.

I also added some attributes to .gitignore in order to not commit invalid files created by Visual Studio.

### CODE REVIEW

**Comment by cremor** [comment]
Seems like you didn't change the async methods. They should always support the same features as the non-async methods in my opinion.

**Comment by marcusvnac** [comment]
I agree with you @cremor, as I'm not using the async methods in my application, I just didn't realized that it was necessary to change then.

I just changed it now. Thanks for your review.

**Comment by ericdc1** [comment]
I really appreciate the work on this but with a change delta of over 900 lines of code there is no way I can feel comfortable merging this. If you can do this in a footprint that I can actually see what changes were just for this I will spend the time reviewing it.

**Comment by marcusvnac** [comment]
Hi @ericdc1 , I'm sad in hearing that because I believe that others maybe still needing this. What I've done is implementing unit tests using the approach already developed in the project. I believe that the unit tests already implemented are there to guarantee that what was working before changes, still working after, no?

I don't know what type of "footprint" you expect, what I can prove to you is that all the unit tests are working after the changes. So, it's up to you to incorporate this changes or not. I've done the best I could with the time I had to work on this.

**Comment by ericdc1** [comment]
Take a look at how many lines of code changed
https://github.com/ericdc1/Dapper.SimpleCRUD/pull/93/files 

Compare that to this pull request which I accepted
https://github.com/ericdc1/Dapper.SimpleCRUD/pull/90/files

If you only change the lines that are required for your change I can review it and know what you changed. With your 900 lines of code changed it looks like you changed most of the project. 

Here is a good article with PR suggestions: http://jsbattig.blogspot.com/2014/09/github-code-reviews-etiquette-for.html

**Comment by marcusvnac** [comment]
I know, but except the .gitignore file, all the other changes are necessary for the correct behavior of the feature. There is no way to change only the Insert method without changing Update and Delete in order to everything works well.

**Comment by ericdc1** [comment]
Those 200 lines in the tests program.cs needed to change?

**Comment by marcusvnac** [comment]
I saw this but it seems to be a merge problem from the tool. I just changed the lines shown in the attached image.

compare_program cs

**Pull request closed without merging**
