### PR TITLE
Added support for multiple schemas within a database, and support for get/delete for tables without an int primary key

### PR DESCRIPTION
**Pull request by psantiago**
This also required changing the testing database from SqlCE to localDB, as SqlCE doesn't support multiple schemas per database (which of course made that feature untestable).

### CODE REVIEW

**Comment by mxmissile** [comment]
How do you specify `dbo` in the schema using `TableAttribute`?

[Table("PhotoGallery_photos",Schema = "portal")] generates `[portal.dbo].[dbo.PhotoGallery_photos]` which does not work.

desired: `portal.dbo.[PhotoGallery_photos]`

**Comment by ericdc1** [comment]
See the tests: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L83

    [Table("CarLog", Schema = "Log")]
    public class CarLog
    {
        public int Id { get; set; }
        public string LogNotes { get; set; }
    }


        public void TestInsertIntoDifferentSchema()
        {
            using (var connection = GetOpenConnection())
            {
                var id = connection.Insert(new CarLog { LogNotes = "blah blah blah" });
                id.IsEqualTo(1);
                connection.Delete<CarLog>(id);

            }
        }

**Comment by psantiago** [comment]
@mxmissile - assuming this is for SQL Server, I believe `portal.dbo.photogallery_photos` would refer to a _different_ database `portal`, with the schema `dbo` and table `photogallery_photos` (ie, not a different schema within the database). The schema attribute is intended for use of multiple schemas within a database, see https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/ownership-and-user-schema-separation-in-sql-server

**Comment by mxmissile** [comment]
I see. I got it to work using a different db connection, or writing my own query. Thanks!

**Pull request merged**
