### PR TITLE
closes #213

### LINKED ISSUE #213: Support for Dapper >= 2.0
Hello,

I was curious whether there was planning on supporting Dapper 2.0.0+.  The .nuspec currently lists Dapper (>= 1.50.5 && < 2.0.0) as dependencies.

I'd be happy top help in any way.

### PR DESCRIPTION
**Pull request by istrupin**
remove 452 support, add support for dapper 2.0+

change dapper dependency and file output in nuspec

Add System.Data.SqlClient to tests project

### CODE REVIEW

**Comment by istrupin** [comment]
Hey @ericdc1  -- I just wanted to check back  in here to see if there was anything else I could do to assist you.

**Comment by ericdc1** [comment]
Sorry for the slow merge. Working on this now. Expect a new Nuget package within the hour.

**Comment by istrupin** [comment]
> Sorry for the slow merge. Working on this now. Expect a new Nuget package within the hour.

No problem at all -- we all have day jobs!  Thanks for accepting the merge and letting me contribute!

**Comment by ericdc1** [comment]
https://www.nuget.org/packages/Dapper.SimpleCRUD/2.2.0

**Pull request merged**
